import { useState } from 'react'
import { ChevronDown, ChevronRight, FileText } from 'lucide-react'
import type { InvestigationReport } from '@/lib/traceback/types'

/**
 * The written deliverable. Collapsed by default — the timeline is what a
 * reviewer reads first; the report is what they export.
 */
export function ReportBlock({
  report,
}: {
  report: NonNullable<InvestigationReport['report']>
}) {
  const [open, setOpen] = useState(false)

  return (
    <section className="border-border bg-card rounded-xl border">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center gap-2 p-4 text-left"
      >
        {open ? (
          <ChevronDown className="h-4 w-4" />
        ) : (
          <ChevronRight className="h-4 w-4" />
        )}
        <FileText className="h-4 w-4" />
        <span className="font-semibold">Investigation report</span>
        <span className="text-muted-foreground ml-auto text-sm">
          generated by {report.generated_by}
        </span>
      </button>

      {open && (
        <div className="border-border space-y-6 border-t p-4">
          <div className="grid gap-6 sm:grid-cols-2">
            <div>
              <h3 className="mb-2 font-semibold">Open questions</h3>
              <ul className="text-muted-foreground list-disc space-y-1 pl-5 text-sm">
                {report.open_questions.map((question) => (
                  <li key={question}>{question}</li>
                ))}
              </ul>
            </div>
            <div>
              <h3 className="mb-2 font-semibold">Recommended containment</h3>
              <ul className="text-muted-foreground list-disc space-y-1 pl-5 text-sm">
                {report.containment_steps.map((step) => (
                  <li key={step}>{step}</li>
                ))}
              </ul>
            </div>
          </div>

          <div>
            <h3 className="mb-2 font-semibold">Markdown</h3>
            <pre className="bg-muted max-h-96 overflow-auto rounded-lg p-3 text-xs whitespace-pre-wrap">
              {report.markdown}
            </pre>
          </div>
        </div>
      )}
    </section>
  )
}
